import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.forbes.com/advisor/au/');
  await expect(page.locator('h1')).toContainText('Smart Financial Decisions Made Simple');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/investing/');
  await expect(page.locator('h1')).toContainText('How To Invest');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'How To Invest', exact: true }).click();
  await expect(page.getByRole('link', { name: 'How To Invest', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/credit-cards/best-credit-cards/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Credit Cards For Australians');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/superannuation/best-default-superannuation-funds-in-australia/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Default Superannuation Funds In 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/car-insurance/best-comprehensive-car-insurance-providers/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Comprehensive Car Insurance Providers in Australia');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/health-insurance/best-private-health-insurance-companies/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Private Health Insurance Providers In Australia');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/life-insurance/best-life-insurance-australia/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Life Insurance Providers For Australians');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/pet-insurance/best-pet-insurance-policies-in-australia/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Comprehensive Pet Insurance Policies In Australia');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/travel-insurance/best-comprehensive-travel-insurance/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Comprehensive Travel Insurance Providers In Australia');
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Subscribe' }).click();
  const page3 = await page3Promise;
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/business/');
  await expect(page.locator('h1')).toContainText('Starting Your Small Business');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Starting Your Small Business' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/investing/cryptocurrency/');
  await expect(page.locator('h1')).toContainText('Investing In Cryptocurrency');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Investing In Cryptocurrency' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/personal-loans/best-personal-loans/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best Personal Loans For Australians');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/au/savings/best-high-interest-savings-accounts/');
  await expect(page.locator('h1')).toContainText('Our Pick Of The Best High-Interest Savings Accounts In Australia');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
});