import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.forbes.com/advisor/ca/');
  await expect(page.locator('h1')).toContainText('Smart Financial Decisions Made Simple');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Smart Financial Decisions' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/credit-cards/best/best-credit-cards/');
  await expect(page.locator('h1')).toContainText('Compare Canada’s Best Credit Cards and Choose Your Perfect Match');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/business/');
  await expect(page.locator('h1')).toContainText('Transform Your Small Business');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/credit-cards/best/cash-back/');
  await expect(page.locator('h1')).toContainText('Best Cash Back Credit Cards In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/mortgages/best-mortgage-lenders/');
  await expect(page.locator('h1')).toContainText('Best Mortgage Lenders In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/mortgages/best-mortgage-rates-in-canada/');
  await expect(page.locator('h1')).toContainText('Best Mortgage Rates In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/personal-loans/best-personal-loans/');
  await expect(page.locator('h1')).toContainText('Best Personal Loans In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/banking/gic/best-gic-rates/');
  await expect(page.locator('h1')).toContainText('Best GIC Rates In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/banking/savings/best-savings-accounts/');
  await expect(page.locator('h1')).toContainText('Best Savings Accounts In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/banking/chequing/best-chequing-accounts/');
  await expect(page.locator('h1')).toContainText('Best Chequing Accounts In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/ca/credit-cards/best/travel/');
  await expect(page.locator('h1')).toContainText('Best Travel Credit Cards In Canada For 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
});