import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.forbes.com/advisor/it/');
  await expect(page.locator('h1')).toContainText('Scelte finanziarie intelligenti in tutta semplicità');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Scelte finanziarie' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/investire/');
  await expect(page.locator('h1')).toContainText('Investire soldi');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Investire soldi' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/investire/criptovalute/');
  await expect(page.locator('h1')).toContainText('Investire in criptovalute');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Investire in criptovalute', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/investire/etf/');
  await expect(page.locator('h1')).toContainText('Investire in ETF');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Investire in ETF' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/carta-di-credito/migliori-carte-di-credito/');
  await expect(page.locator('h1')).toContainText('Le migliori carte di credito nel 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/prestiti/miglior-prestito-online/');
  await expect(page.locator('h1')).toContainText('I migliori prestiti online, la classifica');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/assicurazione-auto/assicurazione-auto-online-economica/');
  await expect(page.locator('h1')).toContainText('Assicurazione auto online più economica nel 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/assicurazione-auto/assicurazione-auto-online-economica/');
  await expect(page.locator('h1')).toContainText('Assicurazione auto online più economica nel 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/assicurazione-viaggio/');
  await expect(page.locator('#best-of-article-lander')).toContainText('Assicurazione viaggio: quando farla e quale scegliere');
  await expect(page.getByRole('link', { name: 'Assicurazione viaggio: quando' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/assicurazione-vita/miglior-assicurazione-vita/');
  await expect(page.locator('h1')).toContainText('La migliore assicurazione vita');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/conto-corrente/miglior-conto-corrente-online/');
  await expect(page.locator('h1')).toContainText('Il miglior conto corrente online: classifica 2025');
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
  await page.goto('https://www.forbes.com/advisor/it/business/');
  await expect(page.locator('h1')).toContainText('Crea il tuo business');
  await expect(page.getByRole('img', { name: 'Crea il tuo business' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Forbes Logo' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Subscribe' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'forbes', exact: true })).toBeVisible();
});