name: Playwright AU Tests

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Create directories
      run: |
        mkdir -p test-results
        mkdir -p screenshots
        mkdir -p reports
      
    - name: Run AU Playwright tests
      run: |
        # Function to add delay
        delay() {
          echo "Waiting for 60 seconds..."
          sleep 60
        }
        
        if npx playwright test tests/AU.spec.ts --reporter=html,json,list; then
          echo "AU ✅ Tests passed" > test-results/status.txt
          delay
        else
          echo "AU ❌ Tests failed" > test-results/status.txt
          delay
        fi
      
    - name: Organize test results
      if: always()
      run: |
        # Move HTML report
        mv playwright-report/* test-results/
        mv test-results/playwright-report.html test-results/$(date +%Y-%m-%d_%H-%M-%S)_report.html
        
        # Move screenshots
        mv screenshots/* test-results/screenshots/
        
        # Move performance reports
        mv reports/* test-results/reports/
        
        # Create summary file
        echo "# Test Run Summary - $(date)" > test-results/summary.md
        echo "## Test Status" >> test-results/summary.md
        cat test-results/status.txt >> test-results/summary.md
        echo "" >> test-results/summary.md
        echo "## Performance Reports" >> test-results/summary.md
        echo "\`\`\`" >> test-results/summary.md
        cat test-results/reports/performance-metrics.csv >> test-results/summary.md
        echo "\`\`\`" >> test-results/summary.md
        echo "" >> test-results/summary.md
        echo "## Screenshots" >> test-results/summary.md
        echo "Screenshots are available in the \`screenshots\` directory" >> test-results/summary.md
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: au-test-results
        path: |
          test-results/
          screenshots/
          reports/
        retention-days: 7 
